import ProcessStats from "@/components/ProcessStats";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About — Geometry of Feeling",
  description:
    "Every piece starts with a human emotion and asks: what mathematical function has the same shape as this feeling?",
};

export default function AboutPage() {
  return (
    <div className="pt-28 pb-16">
      <div className="max-w-content mx-auto px-6">
        <div className="max-w-2xl">
          <h1 className="text-2xl font-mono font-light text-primary mb-12">
            The Concept
          </h1>

          <section className="mb-16">
            <h2 className="text-headline uppercase tracking-widest text-primary mb-6">
              Why Mathematics and Emotion
            </h2>
            <div className="space-y-4">
              <p className="text-body text-secondary">
                Every piece in this collection begins with a question: what does
                this emotion look like as an equation?
              </p>
              <p className="text-body text-secondary">
                Grief decays exponentially — intense at first, diminishing over
                time, but never reaching zero. Growth branches fractally — each
                new level of complexity generated by the same recursive rule.
                Connection follows coupled oscillators — two systems influencing
                each other&apos;s rhythm without ever fully merging.
              </p>
              <p className="text-body text-secondary">
                These are not metaphors. The mathematical functions genuinely
                behave the way the emotions do. The equation at the bottom of
                each piece is not decoration. It is the reason the image looks
                the way it does.
              </p>
            </div>
          </section>

          <section className="mb-16">
            <h2 className="text-headline uppercase tracking-widest text-primary mb-6">
              How Each Series Is Made
            </h2>
            <div className="space-y-4">
              <p className="text-body text-secondary">
                <span className="text-primary">Research.</span> Before a single
                line is rendered, the emotion is studied across millennia of
                human art, philosophy, and science. What does this feeling do
                over time? Does it decay? Oscillate? Branch? Converge?
              </p>
              <p className="text-body text-secondary">
                <span className="text-primary">Mathematical selection.</span>{" "}
                The function class is chosen because its behavior mirrors the
                emotion&apos;s dynamics. Exponential decay for grief. L-system
                branching for growth. Parametric coupling for connection.
              </p>
              <p className="text-body text-secondary">
                <span className="text-primary">Iteration.</span> Hundreds of
                parameter variations are rendered in Python. The palette, the
                density, the negative space — every visual property maps to a
                mathematical parameter.
              </p>
              <p className="text-body text-secondary">
                <span className="text-primary">Human curation.</span> Most
                renders are rejected. The ones that survive pass a simple test:
                does this image make you feel the emotion it claims to
                represent?
              </p>
            </div>
          </section>

          {/* The actual code */}
          <section className="mb-16">
            <h2 className="text-headline uppercase tracking-widest text-primary mb-6">
              The Code
            </h2>
            <div className="bg-primary text-bg p-6 overflow-x-auto mb-4">
              <pre className="text-caption leading-relaxed">
{`# GRIEF — Settling
# f(t) = e^(-λt) · cos(ωt)
t = np.linspace(0, 1, 2000)
lam = 3.5   # decay rate — how fast grief fades
omega = 22  # frequency — how often it returns
ys = baseline + PH*0.44 * np.exp(-lam*t) * np.cos(omega*np.pi*t)`}
              </pre>
            </div>
            <p className="text-body text-secondary italic">
              The decay rate (λ) controls how fast the waves shrink. The
              frequency (ω) controls how often grief returns. The parameters
              were chosen because they felt true.
            </p>
          </section>

          <section className="mb-16">
            <h2 className="text-headline uppercase tracking-widest text-primary mb-6">
              This Is Not AI-Generated Art
            </h2>
            <div className="space-y-4">
              <p className="text-body text-secondary">
                AI image generators — Midjourney, DALL-E, Stable Diffusion —
                take a text prompt and pattern-match against billions of training
                images. They produce visually impressive outputs with no
                underlying mathematical structure, no intentional emotional
                architecture, and no verifiable truth.
              </p>
              <p className="text-body text-secondary">
                We went the opposite direction. We started with the emotion. We
                found the mathematics. We wrote the code. We rendered, evaluated,
                and curated. The process took months. Each series represents
                dozens of hours of research, coding, and aesthetic judgment.
              </p>
              <p className="text-body text-secondary">
                The equation at the bottom of every piece is not a label. It is
                the proof.
              </p>
            </div>

            <div className="border border-border p-6 mt-8">
              <p className="text-body text-secondary italic">
                &ldquo;Built by a human. Rendered in Python. Grounded in
                mathematics. Every piece is the result of asking one question:
                what does this emotion look like as an equation?&rdquo;
              </p>
            </div>
          </section>

          {/* Process stats */}
          <section className="mb-16">
            <h2 className="text-headline uppercase tracking-widest text-primary mb-8">
              By the Numbers
            </h2>
            <ProcessStats />
          </section>

          <section className="mb-16">
            <h2 className="text-headline uppercase tracking-widest text-primary mb-6">
              Art Historical Context
            </h2>
            <div className="space-y-4">
              <p className="text-body text-secondary">
                This work stands in a tradition of artists who used reduction and
                restraint as a means of intensification:
              </p>
              <p className="text-body text-secondary">
                <span className="text-primary">
                  Hasegawa T&#333;haku&apos;s Pine Trees
                </span>{" "}
                — the negative space is as carefully composed as the brushwork.
                What is not painted matters as much as what is.
              </p>
              <p className="text-body text-secondary">
                <span className="text-primary">
                  Mark Rothko&apos;s color fields
                </span>{" "}
                — emotion rendered through large-scale color relationships, with
                no representational content. The feeling is in the field itself.
              </p>
              <p className="text-body text-secondary">
                <span className="text-primary">Agnes Martin&apos;s grids</span>{" "}
                — mathematical structure used as a vehicle for meditative calm.
                The geometry is the experience.
              </p>
              <p className="text-body text-secondary">
                Mathematical Affect adds one dimension to this tradition: every
                visual decision can be traced back to a mathematical function.
                The geometry is not arbitrary. The equation is the reason the
                image looks the way it does.
              </p>
            </div>
          </section>

          <section className="mb-16">
            <h2 className="text-headline uppercase tracking-widest text-primary mb-6">
              The Standard
            </h2>
            <p className="text-lg font-mono font-light text-primary leading-relaxed">
              The final question for every piece: if this were hanging in a
              gallery with no label, would a viewer stop and feel something?
            </p>
          </section>

          <section className="border-t border-border pt-12">
            <p className="text-lg font-mono font-light text-primary leading-relaxed">
              The equation at the bottom of each piece is real. It is the reason
              the image looks the way it does. This is not a style filter applied
              to a photograph. This is what the function actually looks like when
              you render it.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
